logging:
  file:
    name: cx-flow.log
  level:
    com:
      checkmarx: DEBUG
    org:
      apache:
        http:
          wire: DEBUG
      springframework:
        web:
          client:
            RestTemplate: DEBUG

cx-flow:
  bug-tracker: Json
  bug-tracker-impl:
    - CxXml
    - Csv
    - Json
    - GitLab
    - GitHub
    - Azure
    - Rally
  branches:
    - main
  filter-severity:
    - High
    - Medium
    - Low
  filter-category:
    - SQL_Injection
    - Stored_XSS
    - Reflected_XSS_All_Clients
  filter-cwe:
  filter-status:
    - Urgent
    - Confirmed
  mitre-url: https://cwe.mitre.org/data/definitions/%s.html
  wiki-url: https://custodela.atlassian.net/wiki/spaces/AS/pages/79462432/Remediation+Guidance
  codebash-url: https://checkmarx-demo.codebashing.com/courses/
  break-build: false
  zip-exclude: \.git/.*, .*\.png,.*\.zip,.*\.jar,.*\.tgz,.*\.jpg
  track-application-only: false
  web-hook-queue: 20
  scan-result-queue: 8
  scan-resubmit: false
  preserve-project-name: false
  http-connection-timeout:
  http-read-timeout:
  enabled-vulnerability-scanners:
    - sast
  thresholds:
    high: 1
    medium: 2
    low: 3

checkmarx:
  version: 9.6
  username: admin_sast
  password: Vncs@@321!!!
  client-secret: 014DF517-39D1-4453-B7B3-9930C563627C
  base-url: https://checkmarx.viettelidc.lab/
  multi-tenant: true
  incremental: true
  configuration: Default Configuration
  scan-preset: Checkmarx Default
  team: /CxServer
  url: ${checkmarx.base-url}/cxrestapi
  portal-url: ${checkmarx.base-url}/cxwebinterface/Portal/CxWebService.asmx
  sdk-url: ${checkmarx.base-url}/cxwebinterface/SDK/CxSDKWebService.asmx
  portal-wsdl: ${checkmarx.base-url}/Portal/CxWebService.asmx?wsdl
  sdk-wsdl: ${checkmarx.base-url}/SDK/CxSDKWebService.asmx?wsdl
  exclude-files: "*.tst,*.json"
  exclude-folders: ".git/,test/, cxflow/"


json:
  file-name-format: "[NAMESPACE]-[REPO]-[BRANCH]-[TIME].json"
  data-folder: "C:\\tmp"

